### ISSUE TITLE
Georreferenciar locais com grandes números de incidência (Hosana)_Sprint - 2

### ISSUE THREAD

**Issue by BrunaAlmeida13** [Seguranca-Em-Foco/SegurancaEmFoco#29]
Funcionalidade: Verificar  georreferência 
Cenário 1: Georreferência está  OK 
Dado que o  diâmetro geográfico  registrado  é de 20m  de distância
E sua referência  de endereço é válido 
Quando o Segurança em foco for localizar endereço referenciado
Então as imagens  geográfico do endereço referente será apresentada normalmente
Cenário 2: Diâmetro muito grande  
Dado que o imagens panorâmicas possui até 20m de distância  
E se  for processar georreferência 
Então as imagens geográficas  não é apresentada 
E um protocolo é gerado no sistema indicando que as imagens geográfico não foi localizada
E um email é enviado para o usuário que solicitou filmagens via FTP

**Comment by andregblima** [comment]
Faltou a descrição básica desta história. Além disso, especifique o que é "georreferenciamento ok".

**Comment by hosana-art** [comment]
Ok

Em Ter, 12 de mai de 2020 17:58, Andre Gustavo Bastos Lima <
notifications@github.com> escreveu:
